// <auto-generated />
namespace ComPro.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Current_status_moved : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Current_status_moved));
        
        string IMigrationMetadata.Id
        {
            get { return "201808262018396_Current_status_moved"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
