// <auto-generated />
namespace ComPro.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class modify_search_view_model : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(modify_search_view_model));
        
        string IMigrationMetadata.Id
        {
            get { return "201803212227352_modify_search_view_model"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
