// <auto-generated />
namespace ComPro.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class latest_member : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(latest_member));
        
        string IMigrationMetadata.Id
        {
            get { return "201808070002005_latest_member"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
